DROP TABLE IF EXISTS owner CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS place CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS ordera CASCADE;
DROP TABLE IF EXISTS food_ordering_request CASCADE;
